"""
Section U / Blueprint Feature 34 — DreamerV3-inspired Market World Model.

This is the *consumer-facing* wrapper around the RSSM defined in
`ml.architectures.WorldModelBundle`. Audit Issue #2 upgrade:

  - Previous architecture (all of encoder + transition + reward) was three
    separate `Sequential(Linear, ReLU, Linear)` MLPs. The "transition" was a
    1-step MLP, not recurrent — there was no real notion of dynamics over time.
  - New architecture is a proper RSSM (Hafner et al., DreamerV3 / Nature 2025):
    GRU-based deterministic recurrence + stochastic Gaussian latent + prior
    and posterior dynamics + symlog reward head + continue head.

External API kept stable (callers in `memory/write.py`, `self_play/mars.py`,
`memory/cognitive/memrl.py`, the test suite, and Audit Issue #1's online-learning
fix continue to work without changes):

  encode(observation: dict) -> list[float]
  predict_next_state(latent: list[float], action: str) -> list[float]
  predict_reward(latent: list[float], action: str) -> float
  imagine_trajectory(action, n_steps, initial_obs) -> dict
  update_on_trade_close(predicted_outcome, actual_pnl, latent) -> dict

Latent representation changed under the hood: 32 floats → 96 floats
(deter[64] + stoch[32], concatenated). Callers treat it as an opaque list, so
this is invisible to them — but the model file format DOES change, so the
checkpoint must be regenerated by pretrainer.

Online-learning scope (unchanged from previous fix): only the REWARD HEAD is
trained from actual_pnl at trade close. The RSSM's encoder/GRU/prior/posterior
need either supervised next-state targets (we don't capture them yet) or
DreamerV3-style imagined-rollout loss with KL balancing — both deferred.
"""
from pathlib import Path
import structlog

log = structlog.get_logger()

_MODEL_PATH = Path("models/world_model.pth")

_bundle       = None
_optimizer    = None
_last_mtime   = 0.0
_LR           = 1e-4   # conservative — single-sample SGD on each trade close, no batch averaging
_GRAD_CLIP    = 1.0    # max gradient norm — prevents single noisy trade from breaking weights
_PNL_SCALE    = 50.0   # actual_pnl ∼ [-50, +50] → reward target ∼ [-1, 1]

# Action one-hot encoding — fixed order: open_long, open_short, hold, close
_ACTIONS = ("open_long", "open_short", "hold", "close")


def _action_onehot(action: str):
    """Return torch tensor [1, 4] for the action; default to hold."""
    import torch
    idx = _ACTIONS.index(action) if action in _ACTIONS else 2  # default hold
    v = [0.0] * len(_ACTIONS)
    v[idx] = 1.0
    return torch.tensor([v], dtype=torch.float32)


def _load() -> None:
    """Lazy load + mtime-based reload. Resets optimizer when weights change."""
    global _bundle, _optimizer, _last_mtime
    if not _MODEL_PATH.exists():
        return
    mtime = _MODEL_PATH.stat().st_mtime
    if _bundle is not None and mtime == _last_mtime:
        return
    try:
        import torch
        from ml.architectures import WorldModelBundle, inject_into_main
        inject_into_main()
        checkpoint = torch.load(_MODEL_PATH, map_location="cpu", weights_only=False)

        bundle = WorldModelBundle()
        if isinstance(checkpoint, dict) and "encoder" in checkpoint and \
                isinstance(checkpoint["encoder"], torch.nn.Module):
            # Legacy dict-of-modules — incompatible shape (old MLP transition vs new
            # GRU+prior+posterior). Refuse to load; pretrainer must regenerate.
            log.warning("world_model_legacy_format_detected_must_repretrain",
                        path=str(_MODEL_PATH))
            return
        if isinstance(checkpoint, dict):
            # state_dict — try strict load; on shape mismatch, fall back to fresh init.
            try:
                bundle.load_state_dict(checkpoint)
            except Exception as exc:
                log.warning("world_model_state_dict_mismatch_using_fresh",
                            error=str(exc)[:200])
                bundle = WorldModelBundle()  # fresh random init
        else:
            log.warning("world_model_legacy_full_pickle_must_repretrain")
            return

        bundle.eval()
        _bundle = bundle
        _last_mtime = mtime
        _optimizer = None
        log.info("world_model_loaded_rssm",
                 mtime=round(mtime, 2),
                 deter_dim=bundle.DETER_DIM,
                 stoch_dim=bundle.STOCH_DIM,
                 latent_dim=bundle.LATENT_DIM)
    except Exception as exc:
        log.warning("world_model_load_failed_using_fallback", error=str(exc)[:200])


def _save_bundle() -> None:
    """Persist current bundle to disk atomically (temp file + rename)."""
    global _last_mtime
    if _bundle is None:
        return
    try:
        import torch
        tmp = _MODEL_PATH.with_suffix(".pth.tmp")
        torch.save(_bundle.state_dict(), tmp)
        tmp.replace(_MODEL_PATH)
        _last_mtime = _MODEL_PATH.stat().st_mtime
    except Exception as exc:
        log.warning("world_model_save_failed", error=str(exc)[:200])


def _get_optimizer():
    """Lazy-init Adam on reward head only — online learning scope per design note."""
    global _optimizer
    if _optimizer is None and _bundle is not None:
        import torch
        _optimizer = torch.optim.Adam(_bundle.reward.parameters(), lr=_LR)
    return _optimizer


# ─────────────────────────────────────────────────────────────────────────────
# RSSM-core online training (Session 2026-05-21 cont. 5).
# Trains encoder + action_embed + GRU + prior + posterior + reward head jointly
# from each closed trade using a 2-step DreamerV3-style KL-balanced loss.
# ─────────────────────────────────────────────────────────────────────────────
_rssm_optimizer = None
_RSSM_LR        = 3e-5    # gentler than reward-only LR — RSSM core has more params
_KL_BALANCE     = 0.8     # DreamerV3 default — α weights stop-grad-posterior side
_KL_FREE_BITS   = 1.0     # nats per dim, prevents KL collapse
_KL_WEIGHT      = 0.5     # caller-controllable balance vs reward MSE


def _get_rssm_optimizer():
    """Adam over encoder + action_embed + GRU + prior + posterior + reward."""
    global _rssm_optimizer
    if _rssm_optimizer is None and _bundle is not None:
        import torch
        params = (
            list(_bundle.encoder.parameters())
            + list(_bundle.action_embed.parameters())
            + list(_bundle.gru.parameters())
            + list(_bundle.prior.parameters())
            + list(_bundle.posterior.parameters())
            + list(_bundle.reward.parameters())
        )
        _rssm_optimizer = torch.optim.Adam(params, lr=_RSSM_LR)
    return _rssm_optimizer


def _embed_obs(obs: dict):
    """Encode an observation dict to embed tensor [1, EMBED_DIM]. Symlog input
    transform — same as `encode()` external API uses."""
    import torch
    vals = [float(v) for v in obs.values() if isinstance(v, (int, float))]
    vals = (vals + [0.0] * _bundle.OBS_DIM)[:_bundle.OBS_DIM]
    x = torch.tensor(vals, dtype=torch.float32).unsqueeze(0)
    x = torch.sign(x) * torch.log1p(torch.abs(x))
    return _bundle.encoder(x)


def _kl_diag_normal(mu_q, std_q, mu_p, std_p):
    """KL(N(mu_q, std_q²) || N(mu_p, std_p²)) summed over the last dimension."""
    import torch
    return (
        torch.log(std_p / std_q)
        + (std_q ** 2 + (mu_q - mu_p) ** 2) / (2.0 * std_p ** 2)
        - 0.5
    ).sum(dim=-1)


def train_rssm_step(entry_obs: dict, action: str,
                    exit_obs: dict, actual_pnl: float) -> dict:
    """U-05b: Train RSSM core (encoder + GRU + prior + posterior + reward head)
    from one closed trade using a 2-step DreamerV3-style KL-balanced loss.

    Step 1: observe(entry_obs, entry_action)   → (h_1, z_1, prior_1, post_1)
    Step 2: observe(exit_obs,  "hold")         → (h_2, z_2, prior_2, post_2)

    Losses:
      KL_balance = α · KL(sg(post_2) || prior_2)
                 + (1-α) · KL(post_2 || sg(prior_2))
      reward     = MSE(reward_head(h_2, z_2), symlog(target_pnl_normalized))
      total      = _KL_WEIGHT · KL_balance + reward

    Reward loss anchors the latent — without it, KL alone would collapse the
    encoder. KL forces the prior to predict where the posterior actually lands
    after the trade. Both required for meaningful RSSM training.

    Behavior matrix mirrors `update_on_trade_close`:
      - F34 deactivated by governance      → {"status": "f34_inactive"}
      - model not loaded                   → {"status": "no_model"}
      - happy path                         → {"status": "updated", "loss": …}
    """
    try:
        from feature_governance.registry import is_active
        if not is_active("F34"):
            return {"status": "f34_inactive"}
    except Exception:
        pass

    _load()
    if _bundle is None:
        return {"status": "no_model"}

    try:
        import torch, time
        opt = _get_rssm_optimizer()
        if opt is None:
            return {"status": "no_rssm_optimizer"}

        _bundle.train()
        opt.zero_grad()

        embed_entry = _embed_obs(entry_obs)
        embed_exit  = _embed_obs(exit_obs)

        # ── Step 1: observe entry tick with the open action ──────────────
        deter_0, stoch_0 = _bundle.initial_state(batch=1)
        action_oh_open = _action_onehot(
            action if action in _ACTIONS else "hold"
        )
        deter_1, stoch_1, *_ = _bundle.observe_step(
            deter_0, stoch_0, action_oh_open, embed_entry
        )

        # ── Step 2: observe exit tick — bot held the position in between ─
        action_oh_hold = _action_onehot("hold")
        deter_2, stoch_2, prior_m2, prior_s2, post_m2, post_s2 = \
            _bundle.observe_step(deter_1, stoch_1, action_oh_hold, embed_exit)

        # KL-balanced consistency loss (per-sample → mean over batch=1)
        kl_prior_side = _kl_diag_normal(
            post_m2.detach(), post_s2.detach(), prior_m2, prior_s2
        )
        kl_post_side  = _kl_diag_normal(
            post_m2, post_s2, prior_m2.detach(), prior_s2.detach()
        )
        # Free-bits clamp prevents the KL from collapsing to zero
        kl_prior_side = torch.clamp(kl_prior_side, min=_KL_FREE_BITS)
        kl_post_side  = torch.clamp(kl_post_side,  min=_KL_FREE_BITS)
        loss_kl = (
            _KL_BALANCE * kl_prior_side
            + (1.0 - _KL_BALANCE) * kl_post_side
        ).mean()

        # Reward anchor — same symlog scheme as update_on_trade_close uses
        target_natural = max(-1.0, min(1.0, actual_pnl / _PNL_SCALE))
        target_symlog  = _bundle.symlog(
            torch.tensor([[target_natural]], dtype=torch.float32)
        )
        full_2 = torch.cat([deter_2, stoch_2], dim=-1)
        pred_symlog = _bundle.reward(full_2)
        loss_reward = torch.nn.functional.mse_loss(pred_symlog, target_symlog)

        loss = _KL_WEIGHT * loss_kl + loss_reward
        loss.backward()
        # Same grad-norm cap as reward-only path — single noisy trade can't blow weights
        all_params = (
            list(_bundle.encoder.parameters())
            + list(_bundle.action_embed.parameters())
            + list(_bundle.gru.parameters())
            + list(_bundle.prior.parameters())
            + list(_bundle.posterior.parameters())
            + list(_bundle.reward.parameters())
        )
        torch.nn.utils.clip_grad_norm_(all_params, max_norm=_GRAD_CLIP)
        opt.step()
        _bundle.eval()
        _save_bundle()

        loss_val   = float(loss.item())
        kl_val     = float(loss_kl.item())
        reward_val = float(loss_reward.item())
        log.info("world_model_rssm_updated",
                 loss=round(loss_val, 6),
                 loss_kl=round(kl_val, 6),
                 loss_reward=round(reward_val, 6),
                 actual_pnl=round(actual_pnl, 4),
                 action=action)

        try:
            import redis_client as _rcw
            _r = _rcw.get()
            _r.incr("world_model:rssm_updates_count")
            _r.set("world_model:rssm_last_loss", loss_val)
            _r.set("world_model:rssm_last_kl",   kl_val)
            _r.set("world_model:rssm_last_reward_loss", reward_val)
            _r.set("world_model:rssm_last_ts",   int(time.time()))
        except Exception:
            pass

        return {
            "status":     "updated",
            "loss":        loss_val,
            "loss_kl":     kl_val,
            "loss_reward": reward_val,
        }
    except Exception as exc:
        log.error("world_model_rssm_backprop_failed", error=str(exc)[:200])
        return {"status": "rssm_backprop_failed", "error": str(exc)[:200]}


# ─────────────────────────────────────────────────────────────────────────────
# External API — preserved signatures so callers work unchanged
# ─────────────────────────────────────────────────────────────────────────────

def encode(observation: dict) -> list[float]:
    """U-01: Encode raw market observation → latent state (deter+stoch concatenated).

    Returns list[float] of length 96 (was 32 in the old MLP architecture). External
    callers treat this as an opaque blob and pass it back to predict_* — they don't
    care about the dimensionality.

    First call from a fresh observation starts a new RSSM trajectory with zero
    initial deter+stoch and uses the POSTERIOR (observation-conditioned) to produce
    the first latent. This is the right behavior at trade-open time.
    """
    _load()
    if _bundle is None:
        # Hash fallback — only used when model file is missing / failed to load.
        import hashlib
        obs_str = str(sorted(observation.items()))
        h = int(hashlib.md5(obs_str.encode()).hexdigest(), 16)
        return [(h >> i & 0xFF) / 255.0 for i in range(_FALLBACK_DIM)]

    try:
        import torch
        vals = [float(v) for v in observation.values() if isinstance(v, (int, float))]
        vals = (vals + [0.0] * _bundle.OBS_DIM)[:_bundle.OBS_DIM]
        x = torch.tensor(vals, dtype=torch.float32).unsqueeze(0)
        # DreamerV3-style symlog input transform: handles arbitrary observation
        # scales (price=50000, volume=1e6, sentiment=0.5 all coexist in obs).
        # Without this, raw price/volume → Xavier-init weights → encoder output
        # of magnitude 1e5 → GRU amplifies → latent of magnitude 1e5 → reward
        # head saturates regardless of warmup. symlog: sign(x)*log1p(|x|).
        x = torch.sign(x) * torch.log1p(torch.abs(x))

        with torch.no_grad():
            embed = _bundle.encoder(x)
            deter, stoch = _bundle.initial_state(batch=1)
            # Use a neutral "hold" action for the initial observation step.
            action_oh = _action_onehot("hold")
            new_deter, new_stoch, *_ = _bundle.observe_step(deter, stoch, action_oh, embed)
        latent = torch.cat([new_deter, new_stoch], dim=-1).squeeze(0).tolist()
        return latent
    except Exception as exc:
        log.error("world_model_encode_failed", error=str(exc)[:200])
        return [0.0] * (WORLDMODEL_LATENT_DIM if _bundle is None else _bundle.LATENT_DIM)


def predict_next_state(latent: list[float], action: str) -> list[float]:
    """U-02: One imagined transition step — uses RSSM prior (no observation).
    Splits incoming latent into (deter, stoch), runs imagine_step, returns new latent."""
    _load()
    if _bundle is None:
        # Hash-fallback: trivial drift
        action_bias = {"open_long": 0.5, "open_short": -0.5, "hold": 0.0, "close": -0.25}
        a = action_bias.get(action, 0.0)
        return [l + a * 0.01 for l in latent]

    try:
        import torch
        d_dim = _bundle.DETER_DIM
        s_dim = _bundle.STOCH_DIM
        if len(latent) < d_dim + s_dim:
            # Old 32-dim latent from a legacy stored prediction. Pad with zeros.
            latent = latent + [0.0] * (d_dim + s_dim - len(latent))
        deter = torch.tensor(latent[:d_dim],            dtype=torch.float32).unsqueeze(0)
        stoch = torch.tensor(latent[d_dim:d_dim+s_dim], dtype=torch.float32).unsqueeze(0)
        action_oh = _action_onehot(action)
        with torch.no_grad():
            new_deter, new_stoch, *_ = _bundle.imagine_step(deter, stoch, action_oh)
        return torch.cat([new_deter, new_stoch], dim=-1).squeeze(0).tolist()
    except Exception as exc:
        log.error("world_model_transition_failed", error=str(exc)[:200])
        return latent


def predict_reward(latent: list[float], action: str) -> float:
    """U-03: Reward head — symlog-space prediction converted back to natural reward.
    Action parameter is kept in signature for backward compat but the new RSSM's
    reward depends only on (deter, stoch); the action's influence flows through
    predict_next_state."""
    _load()
    if _bundle is None:
        action_bias = {"open_long": 0.1, "open_short": 0.1, "hold": 0.0, "close": -0.05}
        return action_bias.get(action, 0.0)

    try:
        import torch
        d_dim = _bundle.DETER_DIM
        s_dim = _bundle.STOCH_DIM
        if len(latent) < d_dim + s_dim:
            latent = latent + [0.0] * (d_dim + s_dim - len(latent))
        deter = torch.tensor(latent[:d_dim],            dtype=torch.float32).unsqueeze(0)
        stoch = torch.tensor(latent[d_dim:d_dim+s_dim], dtype=torch.float32).unsqueeze(0)
        with torch.no_grad():
            r = _bundle.reward_from_state(deter, stoch)
        return float(r.squeeze())
    except Exception as exc:
        log.error("world_model_reward_failed", error=str(exc)[:200])
        return 0.0


def imagine_trajectory(action: str, n_steps: int, initial_obs: dict) -> dict:
    """U-04: Chain encoder + imagined rollout + reward for n_steps; return outcome distribution."""
    latent = encode(initial_obs)
    rewards = []

    for _ in range(n_steps):
        r = predict_reward(latent, action)
        rewards.append(r)
        latent = predict_next_state(latent, action)

    if not rewards:
        return {"mean_pnl": 0.0, "uncertainty": 1.0, "prob_profit": 0.5, "latent": latent}

    mean_r = sum(rewards) / len(rewards)
    variance = sum((r - mean_r) ** 2 for r in rewards) / len(rewards)
    prob_profit = sum(1 for r in rewards if r > 0) / len(rewards)

    return {
        "mean_pnl": round(mean_r, 4),
        "uncertainty": round(variance ** 0.5, 4),
        "prob_profit": round(prob_profit, 4),
        "latent": latent,
    }


def update_on_trade_close(predicted_outcome: dict, actual_pnl: float,
                          latent: list[float] | None = None) -> dict:
    """U-05: Online learning — Adam SGD step on the reward head from prediction error.

    Trained quantity = reward head only. RSSM core (GRU + prior + posterior) is
    NOT trained from trade close events alone — that needs supervised next-state
    targets or full DreamerV3 imagined-rollout loss with KL balancing. Documented
    in the module header.

    Behavior matrix (unchanged from previous fix, refactored for new shapes):
      - F34 deactivated by governance         → log + return {"status": "f34_inactive"}
      - no latent provided (legacy callers)   → log error magnitude only
      - model not loaded                      → log only
      - happy path                            → forward → MSE in symlog space → backprop → save
    """
    pred = float(predicted_outcome.get("mean_pnl", 0.0))
    error = abs(pred - actual_pnl)

    try:
        from feature_governance.registry import is_active
        if not is_active("F34"):
            log.debug("world_model_update_gated_off", error=round(error, 4))
            return {"status": "f34_inactive"}
    except Exception:
        pass

    if latent is None:
        log.debug("world_model_no_latent_log_only",
                  predicted=round(pred, 4), actual=round(actual_pnl, 4), error=round(error, 4))
        return {"status": "no_latent"}

    _load()
    if _bundle is None:
        log.debug("world_model_no_model_log_only", error=round(error, 4))
        return {"status": "no_model"}

    try:
        import torch
        opt = _get_optimizer()
        if opt is None:
            return {"status": "no_optimizer"}

        d_dim = _bundle.DETER_DIM
        s_dim = _bundle.STOCH_DIM
        if len(latent) < d_dim + s_dim:
            latent = latent + [0.0] * (d_dim + s_dim - len(latent))
        deter = torch.tensor(latent[:d_dim],            dtype=torch.float32).unsqueeze(0)
        stoch = torch.tensor(latent[d_dim:d_dim+s_dim], dtype=torch.float32).unsqueeze(0)

        # Target = symlog-transformed normalized PnL, clipped to [-1, 1].
        target_natural = max(-1.0, min(1.0, actual_pnl / _PNL_SCALE))
        target_symlog = _bundle.symlog(torch.tensor([[target_natural]], dtype=torch.float32))

        _bundle.reward.train()
        opt.zero_grad()
        full = torch.cat([deter, stoch], dim=-1)
        # Predict in symlog space — train against symlog target directly. NO clamp here:
        # clamping the prediction kills the gradient at the boundary, so a randomly-
        # saturated reward head could never recover. Inference uses clamp to bound the
        # returned natural-scale value, but SGD needs unclamped gradient flow.
        pred_symlog = _bundle.reward(full)
        loss = torch.nn.functional.mse_loss(pred_symlog, target_symlog)
        # Blueprint F17 EWC penalty: λ/2 · Σ F_i (θ_i - θ*_i)². Adds only when Fisher
        # has been snapshotted (post-300-trade sleep consolidation). Otherwise no-op.
        # Sleep consolidation runs in a separate Celery worker process — the brain's
        # in-memory _ewc_fisher dict starts empty, so we load_state() from Redis on
        # demand. Cheap (one Redis GET) and idempotent.
        try:
            from feature_governance.registry import is_active as _fg_active_f17
            from ml import continual_learning as _cl
            if _fg_active_f17("F17"):
                if not _cl._ewc_fisher:
                    _cl.load_state()
                if _cl._ewc_fisher and _cl._ewc_params_star:
                    ewc_pen = torch.tensor(0.0)
                    for name, p in _bundle.reward.named_parameters():
                        if name in _cl._ewc_fisher and name in _cl._ewc_params_star:
                            f = torch.tensor(_cl._ewc_fisher[name], dtype=p.dtype, device=p.device)
                            s = torch.tensor(_cl._ewc_params_star[name], dtype=p.dtype, device=p.device)
                            ewc_pen = ewc_pen + (f * (p - s) ** 2).sum()
                    loss = loss + 500.0 * ewc_pen  # λ=1000 → λ/2=500
        except Exception:
            pass
        loss.backward()
        # Grad-norm clipping is what actually bounds single-trade weight movement.
        torch.nn.utils.clip_grad_norm_(_bundle.reward.parameters(), max_norm=_GRAD_CLIP)
        opt.step()
        _bundle.reward.eval()

        _save_bundle()

        loss_val = float(loss.item())
        log.info("world_model_weights_updated",
                 actual_pnl=round(actual_pnl, 4),
                 predicted_pnl=round(pred, 4),
                 target_natural=round(target_natural, 4),
                 loss_symlog=round(loss_val, 6),
                 error_pnl=round(error, 4))
        return {
            "status": "updated",
            "loss": loss_val,
            "target_reward": target_natural,
            "error_pnl": error,
        }
    except Exception as exc:
        log.error("world_model_backprop_failed", error=str(exc)[:200])
        return {"status": "backprop_failed", "error": str(exc)[:200]}


def plan_best_action(observation: dict,
                     candidate_actions: list[str] | None = None,
                     n_rollouts: int = 32,
                     horizon: int = 8) -> dict | None:
    """U-07: Model-Predictive Planning (MPP) — picks the best action by imagined rollout.

    Blueprint Feature 34 / Section 8.8 explicitly demand a "policy optimizer: plans
    sequences of actions through imagined futures (model-predictive planning)" and
    that the Brain "selects the action whose imagined outcomes are most consistently
    profitable across the simulated trajectories". Prior to this function the world
    model could only score a single given action via `imagine_trajectory` — there was
    no action selection, so the world model never informed entry decisions.

    For each candidate action:
      1. Encode the initial observation once → (deter0, stoch0) via posterior.
      2. Sample `n_rollouts` stochastic trajectories of length `horizon` using the
         RSSM prior (stoch is resampled from N(prior_mean, prior_std) each step).
      3. Sum natural-scale reward across the trajectory.
      4. Mean across rollouts = action score; std across rollouts = uncertainty.

    Returns argmax action plus full score dict so the caller can apply a softer
    multiplier rather than a hard veto (see signals/engine.py).

    Returns None when the RSSM bundle is in fallback (no model loaded) so callers
    can degrade gracefully — never crash the hot path.
    """
    _load()
    if _bundle is None:
        return None

    if candidate_actions is None:
        candidate_actions = ["open_long", "open_short", "hold"]

    try:
        import torch
        # 1) Encode observation → posterior (deter0, stoch0). Same symlog input
        #    transform as encode(), so MPP and post-hoc training see the same
        #    observation distribution.
        vals = [float(v) for v in observation.values() if isinstance(v, (int, float))]
        vals = (vals + [0.0] * _bundle.OBS_DIM)[:_bundle.OBS_DIM]
        x = torch.tensor(vals, dtype=torch.float32).unsqueeze(0)
        x = torch.sign(x) * torch.log1p(torch.abs(x))

        with torch.no_grad():
            embed = _bundle.encoder(x)
            deter0, stoch0 = _bundle.initial_state(batch=1)
            init_action = _action_onehot("hold")
            deter0, stoch0, *_ = _bundle.observe_step(deter0, stoch0, init_action, embed)

        action_scores: dict[str, float] = {}
        action_stds: dict[str, float] = {}

        with torch.no_grad():
            for action in candidate_actions:
                action_oh = _action_onehot(action)
                cum_rewards: list[float] = []
                for _ in range(n_rollouts):
                    deter, stoch = deter0.clone(), stoch0.clone()
                    total_r = 0.0
                    for _step in range(horizon):
                        # imagine_step resamples stoch from N(prior_mean, prior_std),
                        # so each rollout traces a different imagined future even
                        # with the same action sequence.
                        deter, stoch, *_ = _bundle.imagine_step(deter, stoch, action_oh)
                        r = _bundle.reward_from_state(deter, stoch).clamp(-100.0, 100.0)
                        total_r += float(r.squeeze())
                    cum_rewards.append(total_r)
                mean_r = sum(cum_rewards) / len(cum_rewards) if cum_rewards else 0.0
                var_r = (sum((r - mean_r) ** 2 for r in cum_rewards) / len(cum_rewards)
                         if cum_rewards else 0.0)
                action_scores[action] = round(mean_r, 4)
                action_stds[action] = round(var_r ** 0.5, 4)

        # cont. 52 — no-trade-baseline normalisation. Before this block the
        # raw `reward_from_state` outputs were the only signal MPP used, and
        # those are biased negative by the world-model's training prior (most
        # historical 8-step rollouts net negative after fees). The bias made
        # `mean_reward` uniformly negative for ALL actions, which (a) leaks
        # a misleading scalar into the consume side and (b) loses information
        # about *relative* preference (open vs hold) — the only thing MPP is
        # supposed to inform.
        #
        # Fix: subtract the `hold` action's score from each candidate. Hold
        # becomes the baseline at 0; positive relative score ⇒ this trade
        # beats doing nothing in the imagined trajectories. Action selection
        # is mathematically invariant to a uniform shift (argmax is the same),
        # so this changes only the reported scalar, not the picked action.
        # Source: arXiv 2506.04358 (risk-aware RL reward formulation).
        hold_score = action_scores.get("hold", 0.0)
        relative_scores = {a: round(s - hold_score, 4)
                           for a, s in action_scores.items()}
        best_action = max(relative_scores, key=relative_scores.get)
        mean_reward = relative_scores[best_action]
        uncertainty = action_stds[best_action]

        # Durable evidence keys — feature_health.F34 check reads these to verify
        # the planning side (separate from the post-hoc training side, which uses
        # world_model:prediction:<trade_id>).
        try:
            import time as _t
            import redis_client
            r_cli = redis_client.get()
            r_cli.incr("world_model:mpp_calls_count")
            r_cli.set("world_model:mpp_last_ts", str(int(_t.time())))
            r_cli.set("world_model:mpp_last_best_action", best_action)
            r_cli.set("world_model:mpp_last_mean_reward", str(round(mean_reward, 4)))
            r_cli.set("world_model:mpp_last_uncertainty", str(round(uncertainty, 4)))
        except Exception:
            pass

        return {
            "best_action": best_action,
            "action_scores": action_scores,
            "relative_scores": relative_scores,
            "action_stds": action_stds,
            "mean_reward": mean_reward,
            "uncertainty": uncertainty,
            "n_rollouts": n_rollouts,
            "horizon": horizon,
        }
    except Exception as exc:
        log.warning("plan_best_action_failed", error=str(exc)[:200])
        return None


def prescreen_strategy(strategy_code: str, n_simulations: int = 50) -> tuple[bool, float]:
    """U-06: Pre-screen new strategy using imagined trajectories."""
    import random
    results = []
    for _ in range(n_simulations):
        obs = {"price": random.uniform(100, 50000), "volume": random.uniform(1e6, 1e9)}
        traj = imagine_trajectory("open_long", 10, obs)
        results.append(traj["mean_pnl"])

    avg_pnl = sum(results) / len(results) if results else 0
    passes = avg_pnl > -0.05
    return passes, round(avg_pnl, 4)


# Used by hash-fallback path when bundle is None.
_FALLBACK_DIM = 32
WORLDMODEL_LATENT_DIM = 96
