"""
Blueprint F8 — Strategy Selector.

Section 4.1 Feature 8 demands:
> Strategy Selector: When the Brain decides to open a trade, the Strategy
> Selector evaluates current market conditions and picks the best-fit
> strategy from the active pool — matching strategy strengths to current
> conditions.

Before 2026-05-21 (cont. 7), `brain/soar.py` read a fixed Redis key per
stage (`bot:strategy_uuid:{min(stage,2)}`) — always the same strategy at
each stage. That blocked F8's full lifecycle: experimental strategies
generated by F36 never got picked, so they never accumulated the 30
paper trades + 7 days that `check_trial_eligible` needs to promote.

This module implements UCB1-style multi-armed bandit selection across
active + experimental strategies, regime-filtered. UCB1 is a clean fit
for the "exploit known winners but periodically explore newcomers"
trade-off that's exactly what the blueprint asks for.

Rule 4 honesty (in PROGRESS.md cont. 7):
  - Bandit is global, not per-pair. Strategies that work on majors but
    not alts get one combined score.
  - UCB exploration constant c=1.4 (≈sqrt(2)) is the textbook default,
    not Brain-learned.
  - The strategy_id assigned at trade open is currently a TAG, not an
    executable. The signal engine still uses its own rules. Selector
    primarily drives the LIFECYCLE (attribution → trial eligibility →
    promotion), not the trading rules themselves. Full rule-execution
    integration is a separate architectural step.
"""
from __future__ import annotations

import math
import random
import time
import structlog

import redis_client
from db import db_conn

log = structlog.get_logger()

_UCB_C            = 1.4       # exploration constant (≈sqrt(2), textbook UCB1)
_CACHE_TTL_SEC    = 60        # per-regime pick cache to avoid hammering postgres
_MIN_REGIME_N     = 3         # below this, fall back to total-stats for the strategy
_PNL_NORMALIZER   = 50.0      # reward = clip(net_pnl_usdt / NORMALIZER, -1, 1)


def select_strategy(regime: str | None, brain_stage: int) -> str | None:
    """Pick a strategy_id (UUID string) for the next trade open.

    UCB1 across active + experimental strategies. Per-regime ranking when
    possible, falls back to total-history when the strategy has too few
    samples in this regime. Returns None only if no candidate strategy
    exists at all (DB empty or all retired).
    """
    regime = regime or "unknown"
    r = redis_client.get()

    # 60s per-regime cache so signals firing in bursts share one decision.
    cache_key = f"selector:cache:{regime}"
    cached = r.get(cache_key)
    if cached:
        return cached

    candidates = _fetch_candidates(regime)
    if not candidates:
        log.warning("strategy_selector_no_candidates", regime=regime)
        try:
            r.incr("selector:regime_pool_empty_count")
            r.set("selector:regime_pool_empty_last_regime", regime)
            r.set("selector:regime_pool_empty_last_ts", int(time.time()))
        except Exception:
            pass
        return None

    scored = []
    total_pulls = max(1, sum(c["n_total"] for c in candidates))
    for c in candidates:
        n_regime = c["n_regime_by"].get(regime, 0)
        if n_regime >= _MIN_REGIME_N:
            mean_reward = c["avg_reward_by_regime"].get(regime, 0.0)
            n_for_ucb   = n_regime
        else:
            mean_reward = c["avg_reward_total"]
            n_for_ucb   = c["n_total"]

        if n_for_ucb == 0:
            # Never-tried strategy → infinite UCB → guaranteed pick. UCB1
            # convention — new arms get tried at least once.
            ucb = float("inf")
        else:
            exploration = _UCB_C * math.sqrt(math.log(total_pulls) / n_for_ucb)
            ucb = mean_reward + exploration

        # Random tie-break key so equal UCBs (especially +∞ for n=0) resolve
        # uniformly across the experimental pool. Without this, the tuple
        # sort falls through to comparing UUIDs and always picks the same one.
        scored.append((ucb, random.random(), c["id"], c["name"], n_for_ucb, mean_reward))

    scored.sort(reverse=True)
    best_ucb, _tie, best_id, best_name, best_n, best_reward = scored[0]
    runner_summary = ",".join(f"{name}={ucb:.3f}" for ucb, _, _, name, _, _ in scored[:3])

    log.info("strategy_selector_pick",
             regime=regime, brain_stage=brain_stage,
             chosen=best_name, chosen_id=best_id,
             chosen_n=best_n, chosen_reward=round(best_reward, 4),
             ucb=round(best_ucb, 4) if math.isfinite(best_ucb) else "inf",
             top3=runner_summary)

    # Cache per-regime + bump global counters.
    try:
        r.setex(cache_key, _CACHE_TTL_SEC, best_id)
        r.incr("selector:picks_count")
        r.set("selector:last_picked_id",  best_id)
        r.set("selector:last_picked_name", best_name)
        r.set("selector:last_picked_ts",   int(time.time()))
        r.sadd("selector:distinct_strategies_picked", best_id)
    except Exception as exc:
        log.warning("strategy_selector_redis_failed", error=str(exc)[:120])

    return best_id


def _fetch_candidates(regime: str) -> list[dict]:
    """Pull candidate strategies + per-regime stats from postgres.

    Strategies whose `entry_overrides.regime_whitelist` exists AND excludes
    the current regime are filtered out here. Without this filter the UCB1
    bandit happily picks bull-only experimental strategies in bear regime,
    every signal then trips the gate at signals/engine.py:840
    (`regime_{regime}_not_in_strategy_whitelist`), and the bot deadlocks
    with ~75% reject rate while open positions sit (cont. 55).

    Strategies with no `regime_whitelist` override are always eligible.

    Returns a list of dicts with id, name, status, n_total, avg_reward_total,
    n_regime_by (dict regime → n), avg_reward_by_regime (dict regime → avg).
    """
    r = redis_client.get()
    with db_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, name, status, entry_overrides FROM strategies "
                "WHERE status IN ('active', 'experimental')"
            )
            raw_rows = cur.fetchall()

            strategies: list[dict] = []
            filtered_out: list[str] = []
            for row in raw_rows:
                sid, name, status, entry_overrides = row
                wl = None
                if isinstance(entry_overrides, dict):
                    wl = entry_overrides.get("regime_whitelist")
                if isinstance(wl, list) and wl and regime not in wl:
                    filtered_out.append(name)
                    continue
                strategies.append({
                    "id": str(sid), "name": name, "status": status,
                    "n_total": 0, "avg_reward_total": 0.0,
                    "n_regime_by": {}, "avg_reward_by_regime": {},
                })

            if filtered_out:
                try:
                    r.incrby("selector:regime_filtered_count", len(filtered_out))
                    r.set("selector:regime_filtered_last_regime", regime)
                    r.set("selector:regime_filtered_last_names",
                          ",".join(filtered_out[:10]))
                    r.set("selector:regime_filtered_last_ts", int(time.time()))
                except Exception:
                    pass
                log.info("strategy_selector_regime_filter",
                         regime=regime,
                         excluded_count=len(filtered_out),
                         excluded=filtered_out[:5],
                         remaining=len(strategies))

            if not strategies:
                return []

            ids = [s["id"] for s in strategies]
            cur.execute(
                "SELECT strategy_id, market_regime, "
                "       COUNT(*) AS n, "
                "       AVG(GREATEST(-1.0, LEAST(1.0, "
                "           net_pnl_usdt / NULLIF(capital_usdt, 0)))) AS avg_r "
                "FROM trades "
                "WHERE status='closed' AND strategy_id = ANY(%s::uuid[]) "
                "GROUP BY strategy_id, market_regime",
                (ids,),
            )
            for sid, regime, n, avg_r in cur.fetchall():
                sid_str = str(sid)
                target = next((s for s in strategies if s["id"] == sid_str), None)
                if target is None or not regime:
                    continue
                n_int = int(n)
                avg_r_f = float(avg_r) if avg_r is not None else 0.0
                target["n_regime_by"][regime] = n_int
                target["avg_reward_by_regime"][regime] = avg_r_f
                target["n_total"] += n_int
                # Running weighted total
                if target["n_total"] > n_int:
                    prev_n = target["n_total"] - n_int
                    target["avg_reward_total"] = (
                        target["avg_reward_total"] * prev_n + avg_r_f * n_int
                    ) / target["n_total"]
                else:
                    target["avg_reward_total"] = avg_r_f

    return strategies
